### ISSUE TITLE
compute_geopotential_on_ml.py (v2019) leads to gribapi error with updated python 3.10

### ISSUE THREAD

**Issue by gisi90** [Open-MSS/data-retrieval#35]
.....
adding gph
Arguments: levelist: range(1, 138), output: mss/ecmwf_forecast.EUR_LL015.20230627T00.036.tmp, t_q: grib/ecmwf_forecast.EUR_LL015.20230627T00.036.ml_tq.grib, z_lnsp: grib/ecmwf_forecast.EUR_LL015.20230627T00.036.ml_lnsp_z.grib
Traceback (most recent call last):
  File "/home/ddp/mss_wms/data_retrieval_for_ipa_mss_wms_atos/data-retrieval//bin/compute_geopotential_on_ml.py", line 283, in <module>
    main()
  File "/home/ddp/mss_wms/data_retrieval_for_ipa_mss_wms_atos/data-retrieval//bin/compute_geopotential_on_ml.py", line 107, in main
    codes_index_add_file(idx, args.t_q)
  File "/usr/local/apps/python3/3.10.10-01/lib/python3.10/site-packages/gribapi/gribapi.py", line 1383, in grib_index_add_file
    GRIB_CHECK(err)
  File "/usr/local/apps/python3/3.10.10-01/lib/python3.10/site-packages/gribapi/gribapi.py", line 226, in GRIB_CHECK
    errors.raise_grib_error(errid)
  File "/usr/local/apps/python3/3.10.10-01/lib/python3.10/site-packages/gribapi/errors.py", line 381, in raise_grib_error
    raise ERROR_MAP[errid](errid)
gribapi.errors.PrematureEndOfFileError: End of resource reached when reading message
.....

Solution: update compute_geopotential_on_ml.py to latest version (2023): https://confluence.ecmwf.int/display/ECC/compute_geopotential_on_ml.py

**Comment by gisi90** [comment]
fixed
